// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
//COLOCAR AQUI AS APIS
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99OAo5UDSFbKCNp9eeXhLn1HjOAE-CvA',
    appId: '1:970550983502:web:be12e8b3f8d75ee036fc1f',
    messagingSenderId: '970550983502',
    projectId: 'odontoorca',
    authDomain: 'odontoorca.firebaseapp.com',
    storageBucket: 'odontoorca.firebasestorage.app',
    measurementId: 'G-4EYMR4XPXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj0XL67lB-3WQkye78201tZ9fenWTFYPc',
    appId: '1:970550983502:android:b89c24b6e45f043936fc1f',
    messagingSenderId: '970550983502',
    projectId: 'odontoorca',
    storageBucket: 'odontoorca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr7tsDLVDVCG5QF36Kc3yyD4ZpukJ6wQU',
    appId: '1:970550983502:ios:9d254d94a588bc5736fc1f',
    messagingSenderId: '970550983502',
    projectId: 'odontoorca',
    storageBucket: 'odontoorca.firebasestorage.app',
    iosBundleId: 'com.example.odontoorca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr7tsDLVDVCG5QF36Kc3yyD4ZpukJ6wQU',
    appId: '1:970550983502:ios:9d254d94a588bc5736fc1f',
    messagingSenderId: '970550983502',
    projectId: 'odontoorca',
    storageBucket: 'odontoorca.firebasestorage.app',
    iosBundleId: 'com.example.odontoorca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB99OAo5UDSFbKCNp9eeXhLn1HjOAE-CvA',
    appId: '1:970550983502:web:f1769a10bbb172ce36fc1f',
    messagingSenderId: '970550983502',
    projectId: 'odontoorca',
    authDomain: 'odontoorca.firebaseapp.com',
    storageBucket: 'odontoorca.firebasestorage.app',
    measurementId: 'G-SZ675CV31W',
  );
}
